/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AiLabRouteImport } from './routes/ai-lab'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as ApprovalsApprovalIdRouteImport } from './routes/approvals.$approvalId'
import { Route as PortalCasesCaseIdRouteImport } from './routes/portal.cases.$caseId'
import { Route as ApiPublicHooksSendMorningDigestRouteImport } from './routes/api/public/hooks/send-morning-digest'
import { Route as ApiPublicHooksProcessRemindersRouteImport } from './routes/api/public/hooks/process-reminders'
import { Route as ApiPublicHooksEscalateOverdueStagesRouteImport } from './routes/api/public/hooks/escalate-overdue-stages'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLabRoute = AiLabRouteImport.update({
  id: '/ai-lab',
  path: '/ai-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => ClientsRoute,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => CasesRoute,
} as any)
const ApprovalsApprovalIdRoute = ApprovalsApprovalIdRouteImport.update({
  id: '/$approvalId',
  path: '/$approvalId',
  getParentRoute: () => ApprovalsRoute,
} as any)
const PortalCasesCaseIdRoute = PortalCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => PortalRoute,
} as any)
const ApiPublicHooksSendMorningDigestRoute =
  ApiPublicHooksSendMorningDigestRouteImport.update({
    id: '/api/public/hooks/send-morning-digest',
    path: '/api/public/hooks/send-morning-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessRemindersRoute =
  ApiPublicHooksProcessRemindersRouteImport.update({
    id: '/api/public/hooks/process-reminders',
    path: '/api/public/hooks/process-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEscalateOverdueStagesRoute =
  ApiPublicHooksEscalateOverdueStagesRouteImport.update({
    id: '/api/public/hooks/escalate-overdue-stages',
    path: '/api/public/hooks/escalate-overdue-stages',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-lab': typeof AiLabRoute
  '/approvals': typeof ApprovalsRouteWithChildren
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/calendar': typeof CalendarRoute
  '/cases': typeof CasesRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/portal': typeof PortalRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/approvals/$approvalId': typeof ApprovalsApprovalIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/cases/$caseId': typeof PortalCasesCaseIdRoute
  '/api/public/hooks/escalate-overdue-stages': typeof ApiPublicHooksEscalateOverdueStagesRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
  '/api/public/hooks/send-morning-digest': typeof ApiPublicHooksSendMorningDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-lab': typeof AiLabRoute
  '/approvals': typeof ApprovalsRouteWithChildren
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/calendar': typeof CalendarRoute
  '/cases': typeof CasesRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/approvals/$approvalId': typeof ApprovalsApprovalIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/portal': typeof PortalIndexRoute
  '/portal/cases/$caseId': typeof PortalCasesCaseIdRoute
  '/api/public/hooks/escalate-overdue-stages': typeof ApiPublicHooksEscalateOverdueStagesRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
  '/api/public/hooks/send-morning-digest': typeof ApiPublicHooksSendMorningDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-lab': typeof AiLabRoute
  '/approvals': typeof ApprovalsRouteWithChildren
  '/auth': typeof AuthRoute
  '/bootstrap': typeof BootstrapRoute
  '/calendar': typeof CalendarRoute
  '/cases': typeof CasesRouteWithChildren
  '/clients': typeof ClientsRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/knowledge-base': typeof KnowledgeBaseRoute
  '/portal': typeof PortalRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/users': typeof UsersRoute
  '/approvals/$approvalId': typeof ApprovalsApprovalIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/cases/$caseId': typeof PortalCasesCaseIdRoute
  '/api/public/hooks/escalate-overdue-stages': typeof ApiPublicHooksEscalateOverdueStagesRoute
  '/api/public/hooks/process-reminders': typeof ApiPublicHooksProcessRemindersRoute
  '/api/public/hooks/send-morning-digest': typeof ApiPublicHooksSendMorningDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-lab'
    | '/approvals'
    | '/auth'
    | '/bootstrap'
    | '/calendar'
    | '/cases'
    | '/clients'
    | '/documents'
    | '/knowledge-base'
    | '/portal'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/approvals/$approvalId'
    | '/cases/$caseId'
    | '/clients/$clientId'
    | '/portal/'
    | '/portal/cases/$caseId'
    | '/api/public/hooks/escalate-overdue-stages'
    | '/api/public/hooks/process-reminders'
    | '/api/public/hooks/send-morning-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-lab'
    | '/approvals'
    | '/auth'
    | '/bootstrap'
    | '/calendar'
    | '/cases'
    | '/clients'
    | '/documents'
    | '/knowledge-base'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/approvals/$approvalId'
    | '/cases/$caseId'
    | '/clients/$clientId'
    | '/portal'
    | '/portal/cases/$caseId'
    | '/api/public/hooks/escalate-overdue-stages'
    | '/api/public/hooks/process-reminders'
    | '/api/public/hooks/send-morning-digest'
  id:
    | '__root__'
    | '/'
    | '/ai-lab'
    | '/approvals'
    | '/auth'
    | '/bootstrap'
    | '/calendar'
    | '/cases'
    | '/clients'
    | '/documents'
    | '/knowledge-base'
    | '/portal'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/approvals/$approvalId'
    | '/cases/$caseId'
    | '/clients/$clientId'
    | '/portal/'
    | '/portal/cases/$caseId'
    | '/api/public/hooks/escalate-overdue-stages'
    | '/api/public/hooks/process-reminders'
    | '/api/public/hooks/send-morning-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiLabRoute: typeof AiLabRoute
  ApprovalsRoute: typeof ApprovalsRouteWithChildren
  AuthRoute: typeof AuthRoute
  BootstrapRoute: typeof BootstrapRoute
  CalendarRoute: typeof CalendarRoute
  CasesRoute: typeof CasesRouteWithChildren
  ClientsRoute: typeof ClientsRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRoute
  PortalRoute: typeof PortalRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  UsersRoute: typeof UsersRoute
  ApiPublicHooksEscalateOverdueStagesRoute: typeof ApiPublicHooksEscalateOverdueStagesRoute
  ApiPublicHooksProcessRemindersRoute: typeof ApiPublicHooksProcessRemindersRoute
  ApiPublicHooksSendMorningDigestRoute: typeof ApiPublicHooksSendMorningDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-lab': {
      id: '/ai-lab'
      path: '/ai-lab'
      fullPath: '/ai-lab'
      preLoaderRoute: typeof AiLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof CasesRoute
    }
    '/approvals/$approvalId': {
      id: '/approvals/$approvalId'
      path: '/$approvalId'
      fullPath: '/approvals/$approvalId'
      preLoaderRoute: typeof ApprovalsApprovalIdRouteImport
      parentRoute: typeof ApprovalsRoute
    }
    '/portal/cases/$caseId': {
      id: '/portal/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/portal/cases/$caseId'
      preLoaderRoute: typeof PortalCasesCaseIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/api/public/hooks/send-morning-digest': {
      id: '/api/public/hooks/send-morning-digest'
      path: '/api/public/hooks/send-morning-digest'
      fullPath: '/api/public/hooks/send-morning-digest'
      preLoaderRoute: typeof ApiPublicHooksSendMorningDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-reminders': {
      id: '/api/public/hooks/process-reminders'
      path: '/api/public/hooks/process-reminders'
      fullPath: '/api/public/hooks/process-reminders'
      preLoaderRoute: typeof ApiPublicHooksProcessRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/escalate-overdue-stages': {
      id: '/api/public/hooks/escalate-overdue-stages'
      path: '/api/public/hooks/escalate-overdue-stages'
      fullPath: '/api/public/hooks/escalate-overdue-stages'
      preLoaderRoute: typeof ApiPublicHooksEscalateOverdueStagesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApprovalsRouteChildren {
  ApprovalsApprovalIdRoute: typeof ApprovalsApprovalIdRoute
}

const ApprovalsRouteChildren: ApprovalsRouteChildren = {
  ApprovalsApprovalIdRoute: ApprovalsApprovalIdRoute,
}

const ApprovalsRouteWithChildren = ApprovalsRoute._addFileChildren(
  ApprovalsRouteChildren,
)

interface CasesRouteChildren {
  CasesCaseIdRoute: typeof CasesCaseIdRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesCaseIdRoute: CasesCaseIdRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface ClientsRouteChildren {
  ClientsClientIdRoute: typeof ClientsClientIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsClientIdRoute: ClientsClientIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface PortalRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
  PortalCasesCaseIdRoute: typeof PortalCasesCaseIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
  PortalCasesCaseIdRoute: PortalCasesCaseIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiLabRoute: AiLabRoute,
  ApprovalsRoute: ApprovalsRouteWithChildren,
  AuthRoute: AuthRoute,
  BootstrapRoute: BootstrapRoute,
  CalendarRoute: CalendarRoute,
  CasesRoute: CasesRouteWithChildren,
  ClientsRoute: ClientsRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  KnowledgeBaseRoute: KnowledgeBaseRoute,
  PortalRoute: PortalRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  UsersRoute: UsersRoute,
  ApiPublicHooksEscalateOverdueStagesRoute:
    ApiPublicHooksEscalateOverdueStagesRoute,
  ApiPublicHooksProcessRemindersRoute: ApiPublicHooksProcessRemindersRoute,
  ApiPublicHooksSendMorningDigestRoute: ApiPublicHooksSendMorningDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
